//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP2023UserDanisV32.DataModel
{
	using SP2023UserDanisV32.Utils;
	using System;
    using System.Collections.Generic;
	using System.Linq;
	using System.Windows.Media;

	public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int AgentTypeID { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string DirectorName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public int Priority { get; set; }
    
        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }

        public ImageSource PhotoSource { get
            {
                if (string.IsNullOrWhiteSpace(Logo))
                    return SingletonManager.AltImage;
                var img = UniversalUtils.SourceFromURI(UniversalUtils.UriForMedia(Logo));
                return (img != null) ? img : SingletonManager.AltImage;
            } }
        
        public string TitleText { get
            {
                return String.Format("{0} | {1}", AgentType.Title, Title);
            } }

        public int SellsInYear { get
            {
                return ProductSale.Where(p => DateTime.Now.Subtract(p.SaleDate).TotalDays <= 365).Sum(p => p.ProductCount);
            } }

        public int CurrentDiscount { get
            {
                decimal sumPrices = ProductSale.Sum(p => p.Product.ProductCostHistory.OrderByDescending(pp => pp.ChangeDate).First().CostValue * p.ProductCount);
                if (sumPrices > 500000)
                    return 25;
                if (sumPrices > 150000)
                    return 20;
                if (sumPrices > 50000)
                    return 10;
                if (sumPrices > 10000)
                    return 5;
                return 0;
            } }

        public int CurrentPriority
        {
            get
            {
                var priorityHistory = AgentPriorityHistory.OrderByDescending(p => p.ChangeDate).FirstOrDefault();
                if (priorityHistory != null)
                    return priorityHistory.PriorityValue;
                return Priority;
            }
        }
	}
}
